# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    staticcheck:
      checks:
        - all

    errcheck:
      check-type-assertions: true
      check-blank: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party/
      - builtin/
      - examples/

formatters:
  enable:
    - gofmt
    - goimports

  exclusions:
    generated: lax
    paths:
      - third_party/
      - builtin/
      - examples/